import os
import glob
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns


def generate_sensitivity_plots(
    results_dir="../paper/sensitivity", output_dir="../paper/plots/sensitivity"
):
    """
    Reads the CSVs generated by run_sensitivity.py and creates line plots.
    """
    script_dir = os.path.dirname(os.path.abspath(__file__))
    results_dir = os.path.join(script_dir, results_dir)
    output_dir = os.path.join(script_dir, output_dir)
    os.makedirs(output_dir, exist_ok=True)

    factors = {
        "noise": "Noise Strength",
        "independence": "Independence Strength",
        "nodes": "Number of Nodes",
        "nq": "Number of Test Queries",
    }

    # Map from the flattened column string format to the display name
    metrics_to_plot = {
        "('Avg_Weighted_Hellinger', 'mean')": (
            "Parameter Fidelity (Weighted Hellinger)",
            "Lower is better",
        ),
        "('Inf_Accuracy', 'mean')": ("Inference Accuracy", "Higher is better"),
        "('Dec_Regret', 'mean')": ("Decision Regret", "Lower is better"),
        "('Avg_Time_Sec', 'mean')": ("Runtime (Seconds)", "Lower is better"),
    }

    sns.set_theme(style="whitegrid", context="paper", font_scale=1.2)
    strategy_order = [
        "Baseline MLE",
        "Synthetic EM",
        "Iterative Proportional Fitting",
        "Copula Optimization",
        "Constraint Optimization",
        "MCMC Optimization",
        "Random Guess",
    ]
    palette = sns.color_palette("Set2", n_colors=len(strategy_order))
    strategy_colors = {
        name: palette[i] for i, name in enumerate(strategy_order)
    }

    if not os.path.exists(results_dir):
        print(
            f"Directory {results_dir} not found. Please run sensitivity experiments first."
        )
        return

    for prefix, factor_name in factors.items():
        pattern = os.path.join(results_dir, f"{prefix}_*.csv")
        files = glob.glob(pattern)

        if not files:
            continue

        print(f"Processing factor: {factor_name}")

        combined_df = []
        for f in files:
            val_str = (
                os.path.basename(f)
                .replace(f"{prefix}_", "")
                .replace(".csv", "")
            )
            try:
                val = float(val_str)
            except ValueError:
                continue

            combined_df = []
        for f in files:
            val_str = (
                os.path.basename(f)
                .replace(f"{prefix}_", "")
                .replace(".csv", "")
            )
            try:
                val = float(val_str)
            except ValueError:
                continue

            # Read CSV with a 2-level header
            df = pd.read_csv(f, header=[0, 1])

            # Flatten columns: if the top level is 'Strategy' or 'Unnamed: 0',
            # make it exactly 'Strategy'. Otherwise, format as "('Metric', 'mean')"
            new_cols = []
            for col_tuple in df.columns:
                top_level = str(col_tuple[0])
                if "Unnamed" in top_level or "Strategy" in top_level:
                    new_cols.append("Strategy")
                else:
                    # e.g., creates the exact string "('Avg_Weighted_Hellinger', 'mean')"
                    new_cols.append(f"('{col_tuple[0]}', '{col_tuple[1]}')")

            df.columns = new_cols

            # Drop the empty row that pd.read_csv sometimes leaves behind
            # (where 'Strategy' column contains NaN or 'mean' due to the MultiIndex spacing)
            df = df.dropna(subset=["Strategy"])
            df = df[df["Strategy"] != "mean"]

            df["Factor_Value"] = val
            combined_df.append(df)

        if not combined_df:
            continue

        full_data = pd.concat(combined_df, ignore_index=True)
        # Convert numeric metrics back to float (just in case they were read as object strings)
        for c in full_data.columns:
            if c not in ["Strategy", "Factor_Value"]:
                full_data[c] = pd.to_numeric(full_data[c], errors="coerce")

        full_data = full_data.sort_values("Factor_Value")

        strategies = full_data["Strategy"].unique()
        strategies = sorted(
            strategies,
            key=lambda s: (
                strategy_order.index(s)
                if s in strategy_order
                else len(strategy_order)
            ),
        )
        strategies = [s for s in strategies if s != "Strategy"]

        # Plot each requested metric
        for metric_col, (
            metric_name,
            label_direction,
        ) in metrics_to_plot.items():
            if metric_col not in full_data.columns:
                continue

            plt.figure(figsize=(7, 5))

            for strategy in strategies:
                strat_data = full_data[full_data["Strategy"] == strategy]

                # The std column string
                std_col = metric_col.replace("'mean'", "'std'")

                if (
                    std_col in full_data.columns
                    and not strat_data[std_col].isna().all()
                ):
                    plt.errorbar(
                        strat_data["Factor_Value"],
                        strat_data[metric_col],
                        yerr=strat_data[std_col],
                        label=strategy,
                        color=strategy_colors.get(strategy, "gray"),
                        marker="o",
                        capsize=4,
                        capthick=1.5,
                        elinewidth=1.5,
                        markersize=6,
                        linestyle="-",
                        linewidth=2,
                        alpha=0.85,
                    )
                else:
                    plt.plot(
                        strat_data["Factor_Value"],
                        strat_data[metric_col],
                        label=strategy,
                        color=strategy_colors.get(strategy, "gray"),
                        marker="o",
                        markersize=6,
                        linestyle="-",
                        linewidth=2,
                        alpha=0.2,
                    )

            # Formatting
            plt.title(f"{metric_name} vs. {factor_name}", fontsize=14, pad=15)
            plt.xlabel(factor_name, fontsize=12)
            plt.ylabel(f"{metric_name}\n({label_direction})", fontsize=12)

            if "Runtime" in metric_name and prefix in ["nodes", "nq"]:
                plt.yscale("log")
                plt.ylabel(
                    f"{metric_name} (Log Scale)\n({label_direction})",
                    fontsize=12,
                )

            plt.legend(
                loc="upper center",
                bbox_to_anchor=(0.5, -0.18),
                ncol=3,
                frameon=True,
            )

            if prefix in ["nodes", "nq"]:
                plt.xticks(full_data["Factor_Value"].unique())

            plt.tight_layout()

            # Save
            safe_metric_name = (
                metric_name.replace(" ", "_").replace("(", "").replace(")", "")
            )
            plot_filename = os.path.join(
                output_dir, f"{prefix}_{safe_metric_name}.pdf"
            )
            plt.savefig(plot_filename, bbox_inches="tight", dpi=300)
            plt.close()
            print(f"  -> Saved {plot_filename}")


if __name__ == "__main__":
    generate_sensitivity_plots()
